export const SLOTS = [
  { id: "rifle", name: "RIFLE", key: "1" },
  { id: "pistol", name: "PISTOL", key: "2" },
  { id: "knife", name: "KNIFE", key: "3" },
  { id: "grenade", name: "GRENADE", key: "4" },
];

export const WEAPONS = [
  {
    id: "ar-vector",
    name: "M4A1 VECTOR",
    caliber: "5.56 NATO",
    className: "ASSAULT RIFLE",
    slot: "rifle",
    kind: "firearm",
    price: 0,
    damage: 22,
    rpm: 750,
    magazine: 30,
    reserve: 150,
    reloadTime: 1.65,
    auto: true,
    pellets: 1,
    range: 120,
    falloff: 0.42,
    hipSpread: 0.006,
    adsSpread: 0.0015,
    recoil: 0.0125,
    adsFov: 55,
    build: { barrel: 0.48, muzzle: 1.24, magazine: 0.22, stock: 0.38, optic: "acog" },
  },
  {
    id: "smg-wasp",
    name: "MP9 WASP",
    caliber: "9x19 PARA",
    className: "CARBINE",
    slot: "rifle",
    kind: "firearm",
    price: 850,
    damage: 15,
    rpm: 1020,
    magazine: 35,
    reserve: 175,
    reloadTime: 1.35,
    auto: true,
    pellets: 1,
    range: 70,
    falloff: 0.62,
    hipSpread: 0.009,
    adsSpread: 0.0028,
    recoil: 0.0085,
    adsFov: 62,
    build: { barrel: 0.26, muzzle: 0.92, magazine: 0.26, stock: 0.16, optic: "micro" },
  },
  {
    id: "sr-longbow",
    name: "LONGBOW A7",
    caliber: ".338 LAPUA",
    className: "MARKSMAN RIFLE",
    slot: "rifle",
    kind: "firearm",
    price: 3200,
    damage: 92,
    rpm: 48,
    magazine: 5,
    reserve: 35,
    reloadTime: 2.6,
    auto: false,
    pellets: 1,
    range: 200,
    falloff: 0.08,
    hipSpread: 0.045,
    adsSpread: 0.0002,
    recoil: 0.055,
    adsFov: 24,
    build: { barrel: 0.92, muzzle: 1.62, magazine: 0.14, stock: 0.46, optic: "scope" },
  },
  {
    id: "px-9",
    name: "PX-9 SIDEARM",
    caliber: "9x19 PARA",
    className: "PISTOL",
    slot: "pistol",
    kind: "firearm",
    price: 0,
    damage: 18,
    rpm: 380,
    magazine: 15,
    reserve: 75,
    reloadTime: 1.15,
    auto: false,
    pellets: 1,
    range: 55,
    falloff: 0.55,
    hipSpread: 0.012,
    adsSpread: 0.0035,
    recoil: 0.018,
    adsFov: 64,
    build: { barrel: 0.16, muzzle: 0.62, magazine: 0.16, stock: 0, optic: "none" },
  },
  {
    id: "de-50",
    name: "DEAGLE 50",
    caliber: ".50 AE",
    className: "HAND CANNON",
    slot: "pistol",
    kind: "firearm",
    price: 1400,
    damage: 48,
    rpm: 160,
    magazine: 7,
    reserve: 35,
    reloadTime: 1.45,
    auto: false,
    pellets: 1,
    range: 80,
    falloff: 0.28,
    hipSpread: 0.018,
    adsSpread: 0.004,
    recoil: 0.038,
    adsFov: 60,
    build: { barrel: 0.22, muzzle: 0.78, magazine: 0.18, stock: 0, optic: "micro" },
  },
  {
    id: "knife-combat",
    name: "KA-BAR",
    caliber: "MELEE",
    className: "COMBAT KNIFE",
    slot: "knife",
    kind: "melee",
    price: 0,
    damage: 58,
    rpm: 110,
    magazine: 1,
    reserve: 0,
    reloadTime: 0.4,
    auto: false,
    pellets: 1,
    range: 2.35,
    falloff: 0.05,
    hipSpread: 0,
    adsSpread: 0,
    recoil: 0.004,
    adsFov: 70,
    build: { blade: 0.42 },
  },
  {
    id: "knife-tanto",
    name: "SHADOW TANTO",
    caliber: "MELEE",
    className: "TANTO",
    slot: "knife",
    kind: "melee",
    price: 900,
    damage: 74,
    rpm: 95,
    magazine: 1,
    reserve: 0,
    reloadTime: 0.4,
    auto: false,
    pellets: 1,
    range: 2.55,
    falloff: 0.04,
    hipSpread: 0,
    adsSpread: 0,
    recoil: 0.003,
    adsFov: 70,
    build: { blade: 0.5 },
  },
  {
    id: "frag-mk3",
    name: "MK3 FRAG",
    caliber: "HE",
    className: "GRENADE",
    slot: "grenade",
    kind: "grenade",
    price: 0,
    damage: 78,
    rpm: 48,
    magazine: 2,
    reserve: 4,
    reloadTime: 1.1,
    auto: false,
    pellets: 1,
    range: 6.5,
    falloff: 0.85,
    hipSpread: 0.01,
    adsSpread: 0.01,
    recoil: 0.02,
    adsFov: 72,
    fuse: 1.65,
    throwSpeed: 17,
    build: { body: 0.07 },
  },
  {
    id: "impact-viper",
    name: "VIPER IMPACT",
    caliber: "HE",
    className: "IMPACT GRENADE",
    slot: "grenade",
    kind: "grenade",
    price: 1100,
    damage: 62,
    rpm: 70,
    magazine: 3,
    reserve: 6,
    reloadTime: 0.9,
    auto: false,
    pellets: 1,
    range: 5.2,
    falloff: 0.7,
    hipSpread: 0.008,
    adsSpread: 0.008,
    recoil: 0.016,
    adsFov: 72,
    fuse: 0.08,
    throwSpeed: 19,
    build: { body: 0.065 },
  },
];

export const SKINS = [
  { id: "standard", name: "STANDARD ISSUE", price: 0, body: 0x171b19, accent: 0x303830, metal: 0x4c534e, gloss: 0.36 },
  { id: "desert", name: "DESERT TAN", price: 400, body: 0x8a7351, accent: 0xb59a69, metal: 0x6d6250, gloss: 0.55 },
  { id: "arctic", name: "ARCTIC SPLINTER", price: 650, body: 0xd8dee2, accent: 0x8fa0ab, metal: 0x9aa7ad, gloss: 0.28 },
  { id: "carbon", name: "CARBON EDGE", price: 1100, body: 0x0e1011, accent: 0x2b3033, metal: 0x3d4347, gloss: 0.14 },
  { id: "viper", name: "NEON VIPER", price: 1900, body: 0x14181a, accent: 0x2fe08a, metal: 0x3f4b46, gloss: 0.22, emissive: 0x2fe08a },
  { id: "gilded", name: "GILDED ROYALE", price: 3400, body: 0x2a220f, accent: 0xd9a933, metal: 0xc79a2e, gloss: 0.18, emissive: 0x53360a },
];

export const starterIds = () =>
  SLOTS.map((slot) => WEAPONS.find((weapon) => weapon.slot === slot.id && weapon.price === 0).id);

export const defaultLoadout = () =>
  Object.fromEntries(SLOTS.map((slot) => [slot.id, WEAPONS.find((weapon) => weapon.slot === slot.id && weapon.price === 0).id]));

export const getWeapon = (id) => WEAPONS.find((weapon) => weapon.id === id) ?? WEAPONS[0];
export const getSkin = (id) => SKINS.find((skin) => skin.id === id) ?? SKINS[0];
export const weaponsInSlot = (slot) => WEAPONS.filter((weapon) => weapon.slot === slot);

export const GEM_REWARDS = { kill: 15, headshot: 10, pvpKill: 30, victory: 120 };
